linters:
  phpcs:
    standard: PSR2
    exclude: 'Squiz.Classes.ValidClassName,PSR1.Classes.ClassDeclaration'
  csslint:
    ignore: 'ids,known-properties'
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'vendor/*'
